command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "SERVING_ENDPOINT"
    value: "agents_ankit_yadav-dbdemos-system_consumption_agent"
  - name: "PYTHONPATH"
    value: "."